name: Build sqlx-cli Linux amd64 musl
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      # 安装musl系统工具包
      - name: Install musl-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup target add x86_64-unknown-linux-musl
          rustup override set stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build static release binary
        run: |
          cd sqlx-cli
          cargo build --release \
            --target x86_64-unknown-linux-musl \
            --no-default-features \
            --features rustls,postgres,mysql,sqlite
          mv target/x86_64-unknown-linux-musl/release/sqlx ./sqlx-cli-linux-amd64-musl
          sha256sum sqlx-cli-linux-amd64-musl > sha256sum.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlx-cli-linux-amd64-musl
          path: |
            sqlx-cli/sqlx-cli-linux-amd64-musl
            sqlx-cli/sha256sum.txt
