name: Build sqlx-cli Linux amd64 musl
on:
  workflow_dispatch: #手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          targets: x86_64-unknown-linux-musl

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2

      - name: Build static release binary
        run: |
          cd sqlx-cli
          cargo build --release \
            --target x86_64-unknown-linux-musl \
            --no-default-features \
            --features rustls,postgres,mysql,sqlite
          mv target/x86_64-unknown-linux-musl/release/sqlx ./sqlx-cli-linux-amd64-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlx-cli-linux-amd64-musl
          path: sqlx-cli/sqlx-cli-linux-amd64-musl
